/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ModeloTabelaCliente;
import Controller.OperacaoCadastro;
import Model.Cliente;
import java.util.ArrayList;

/**
 *
 * @author mp
 */
public class JanelaCliente extends javax.swing.JDialog {
    
    private ModeloTabelaCliente modeloTabelaCliente;
    /**
     * Creates new form JanelaCliente
     */
    public JanelaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modeloTabelaCliente = new ModeloTabelaCliente(new ArrayList<Cliente>());
        gradeCliente.setModel(modeloTabelaCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buInserirCliente = new javax.swing.JButton();
        buRemoverCliente = new javax.swing.JButton();
        buAlterarCliente = new javax.swing.JButton();
        buSelecionarCliente = new javax.swing.JButton();
        buSairJanelaCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradeCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buInserirCliente.setText("Inserir");
        buInserirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buInserirClienteActionPerformed(evt);
            }
        });

        buRemoverCliente.setText("Remover");
        buRemoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buRemoverClienteActionPerformed(evt);
            }
        });

        buAlterarCliente.setText("Alterar");
        buAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buAlterarClienteActionPerformed(evt);
            }
        });

        buSelecionarCliente.setText("Selecionar");
        buSelecionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buSelecionarClienteActionPerformed(evt);
            }
        });

        buSairJanelaCliente.setText("Sair");
        buSairJanelaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buSairJanelaClienteActionPerformed(evt);
            }
        });

        gradeCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(gradeCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buSelecionarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buRemoverCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buInserirCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buAlterarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buSairJanelaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(buInserirCliente)
                .addGap(35, 35, 35)
                .addComponent(buRemoverCliente)
                .addGap(33, 33, 33)
                .addComponent(buAlterarCliente)
                .addGap(26, 26, 26)
                .addComponent(buSelecionarCliente)
                .addGap(27, 27, 27)
                .addComponent(buSairJanelaCliente)
                .addContainerGap(187, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buInserirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buInserirClienteActionPerformed

        Cliente cliente = new Cliente();
        if(JanelaCadastroCliente.execultar(null, OperacaoCadastro.ocIncluir, cliente)){
           modeloTabelaCliente.incluirCliente(cliente);
            
            
        }
        
        
    }//GEN-LAST:event_buInserirClienteActionPerformed

    private void buRemoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buRemoverClienteActionPerformed
        int indice = gradeCliente.getSelectedRow();
        if(indice>=0){
            modeloTabelaCliente.excluirCliente(indice);
        
        
        }
        
        
        
        
        
        
    }//GEN-LAST:event_buRemoverClienteActionPerformed

    private void buAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buAlterarClienteActionPerformed

        int indice = gradeCliente.getSelectedRow();
        if(indice >= 0){
            Cliente cliente = modeloTabelaCliente.obterCliente(indice);
            if(JanelaCadastroCliente.execultar(null, OperacaoCadastro.ocAlterar, cliente)){
                modeloTabelaCliente.atualizarCliente(indice, cliente);
            
            }
        
        }
        
    }//GEN-LAST:event_buAlterarClienteActionPerformed

    private void buSelecionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buSelecionarClienteActionPerformed
        
        int indice = gradeCliente.getSelectedRow();
        if(indice >=0){
            Cliente cliente=modeloTabelaCliente.obterCliente(indice);
            JanelaCadastroCliente.execultar(null, OperacaoCadastro.ocConsultar, cliente);
            
        
        }

    }//GEN-LAST:event_buSelecionarClienteActionPerformed

    private void buSairJanelaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buSairJanelaClienteActionPerformed
        dispose();
    }//GEN-LAST:event_buSairJanelaClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaCliente dialog = new JanelaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buAlterarCliente;
    private javax.swing.JButton buInserirCliente;
    private javax.swing.JButton buRemoverCliente;
    private javax.swing.JButton buSairJanelaCliente;
    private javax.swing.JButton buSelecionarCliente;
    private javax.swing.JTable gradeCliente;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
