/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ModeloTabelaProduto;
import Controller.OperacaoCadastro;
import Model.Produto;
import java.util.ArrayList;

/**
 *
 * @author mp
 */
public class JanelaProduto extends javax.swing.JDialog {

    /**
     * Creates new form JanelaProduto
     */
    
    private ModeloTabelaProduto modeloTabelaProduto;
    
    public JanelaProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modeloTabelaProduto = new ModeloTabelaProduto(new ArrayList<Produto>());
        gradeProduto.setModel(modeloTabelaProduto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buInserirProduto = new javax.swing.JButton();
        buRemoverProduto = new javax.swing.JButton();
        buAlterarProduto = new javax.swing.JButton();
        buSelecionarProduto = new javax.swing.JButton();
        buSairJanelaProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradeProduto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buInserirProduto.setText("Inserir");
        buInserirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buInserirProdutoActionPerformed(evt);
            }
        });

        buRemoverProduto.setText("Remover");
        buRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buRemoverProdutoActionPerformed(evt);
            }
        });

        buAlterarProduto.setText("Alterar");
        buAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buAlterarProdutoActionPerformed(evt);
            }
        });

        buSelecionarProduto.setText("Selecionar");
        buSelecionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buSelecionarProdutoActionPerformed(evt);
            }
        });

        buSairJanelaProduto.setText("Sair");
        buSairJanelaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buSairJanelaProdutoActionPerformed(evt);
            }
        });

        gradeProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(gradeProduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buInserirProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buRemoverProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buAlterarProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buSelecionarProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(buSairJanelaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(buInserirProduto)
                        .addGap(31, 31, 31)
                        .addComponent(buRemoverProduto)
                        .addGap(28, 28, 28)
                        .addComponent(buAlterarProduto)
                        .addGap(28, 28, 28)
                        .addComponent(buSelecionarProduto)
                        .addGap(29, 29, 29)
                        .addComponent(buSairJanelaProduto))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buRemoverProdutoActionPerformed

        int indice = gradeProduto.getSelectedRow();
        if(indice >=0){
            modeloTabelaProduto.excluirProduto(indice);
        }
    }//GEN-LAST:event_buRemoverProdutoActionPerformed

    private void buInserirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buInserirProdutoActionPerformed
        
        Produto produto = new Produto();
        if(JanelaCadastroProduto.executar(null, OperacaoCadastro.ocIncluir, produto)){
            modeloTabelaProduto.incluirProduto(produto);
        
        }
        
        
    }//GEN-LAST:event_buInserirProdutoActionPerformed

    private void buAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buAlterarProdutoActionPerformed

        int indice = gradeProduto.getSelectedRow();
        if(indice >=0){
            Produto produto = modeloTabelaProduto.obterProduto(indice);
            if(JanelaCadastroProduto.executar(null, OperacaoCadastro.ocAlterar, produto)){
                modeloTabelaProduto.atualizarProduto(indice, produto);
        
        }
        
        }
        
        
    }//GEN-LAST:event_buAlterarProdutoActionPerformed

    private void buSelecionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buSelecionarProdutoActionPerformed
        
        int indice = gradeProduto.getSelectedRow();
        if(indice>=0){
            Produto produto= modeloTabelaProduto.obterProduto(indice);
            JanelaCadastroProduto.executar(null, OperacaoCadastro.ocConsultar, produto);
        
        }
    }//GEN-LAST:event_buSelecionarProdutoActionPerformed

    private void buSairJanelaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buSairJanelaProdutoActionPerformed
       dispose();
    }//GEN-LAST:event_buSairJanelaProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaProduto dialog = new JanelaProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buAlterarProduto;
    private javax.swing.JButton buInserirProduto;
    private javax.swing.JButton buRemoverProduto;
    private javax.swing.JButton buSairJanelaProduto;
    private javax.swing.JButton buSelecionarProduto;
    private javax.swing.JTable gradeProduto;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
