/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author mp
 */
public class JanelaPrincipal extends javax.swing.JDialog {

    /**
     * Creates new form JanelaPrincipal
     */
    private JanelaCliente janelaCliente;
    private JanelaProduto janelaProduto;
    private JanelaVenda janelaVenda;
    private JanelaRelatorio janelaRelatorio;
    
    public JanelaPrincipal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        janelaRelatorio = new JanelaRelatorio(null,true);
        janelaCliente = new JanelaCliente(null,true);
        janelaProduto = new JanelaProduto(null,true);
        janelaVenda = new JanelaVenda(null,true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buCadastrarCliente = new javax.swing.JButton();
        buCadastrarProduto = new javax.swing.JButton();
        buCadastrarVenda = new javax.swing.JButton();
        buSairPrograma = new javax.swing.JButton();
        burelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buCadastrarCliente.setText("Cadastrar um novo Cliente");
        buCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCadastrarClienteActionPerformed(evt);
            }
        });

        buCadastrarProduto.setText("Cadastrar um novo Produto");
        buCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCadastrarProdutoActionPerformed(evt);
            }
        });

        buCadastrarVenda.setText("Cadastrar um venda");
        buCadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCadastrarVendaActionPerformed(evt);
            }
        });

        buSairPrograma.setText("Sair ");
        buSairPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buSairProgramaActionPerformed(evt);
            }
        });

        burelatorio.setText("Relatório");
        burelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buCadastrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(buCadastrarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buSairPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buCadastrarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(burelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(buCadastrarCliente)
                .addGap(41, 41, 41)
                .addComponent(buCadastrarProduto)
                .addGap(39, 39, 39)
                .addComponent(buCadastrarVenda)
                .addGap(36, 36, 36)
                .addComponent(burelatorio)
                .addGap(30, 30, 30)
                .addComponent(buSairPrograma)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void burelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burelatorioActionPerformed
        
        
        janelaRelatorio.setLocationRelativeTo(null);
        janelaRelatorio.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_burelatorioActionPerformed

    private void buCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCadastrarClienteActionPerformed

       
        janelaCliente.setLocationRelativeTo(null);
        janelaCliente.setVisible(true);





       
    }//GEN-LAST:event_buCadastrarClienteActionPerformed

    private void buCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCadastrarProdutoActionPerformed

       
        janelaProduto.setLocationRelativeTo(null);
        janelaProduto.setVisible(true);




      
    }//GEN-LAST:event_buCadastrarProdutoActionPerformed

    private void buCadastrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCadastrarVendaActionPerformed
        
        janelaVenda.setLocationRelativeTo(null);
        janelaVenda.setVisible(true);




    }//GEN-LAST:event_buCadastrarVendaActionPerformed

    private void buSairProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buSairProgramaActionPerformed

        dispose();

       
    }//GEN-LAST:event_buSairProgramaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaPrincipal dialog = new JanelaPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buCadastrarCliente;
    private javax.swing.JButton buCadastrarProduto;
    private javax.swing.JButton buCadastrarVenda;
    private javax.swing.JButton buSairPrograma;
    private javax.swing.JButton burelatorio;
    // End of variables declaration//GEN-END:variables
}
